apiVersion: v1
kind: Pod
metadata:
  name: cpu-test
  namespace: default
spec:
  containers:
    - name: cpu
      image: busybox
      command: ['sh', '-c', 'while true; do yes > /dev/null; done']
      resources:
        requests:
          cpu: 10m