apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-high-cpu-usage
  namespace: monitoring
spec:
  groups:
    - name: pod.rules
      rules:
        - alert: PodHighCPU
          expr: sum(rate(container_cpu_usage_seconds_total{container!="",pod!=""}[1m])) by (pod, namespace) * 100 > 80
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod has high CPU usage (over 80%)"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using more than 80% CPU for 1 minute."
